# Generated by Django 3.2.6 on 2021-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_auto_20210824_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consulted',
            field=models.IntegerField(default=0),
        ),
    ]
