# Generated by Django 3.2.6 on 2021-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0004_auto_20210824_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
