# Generated by Django 3.2.6 on 2021-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
